# Generated by Django 3.1.3 on 2021-06-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210607_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='user',
            new_name='author',
        ),
    ]
