# Generated by Django 3.1.3 on 2021-06-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
