# Generated by Django 3.1.3 on 2021-06-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bids',
        ),
    ]
