# Generated by Django 3.1.3 on 2021-07-09 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210707_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
