# Generated by Django 3.1.3 on 2021-07-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210711_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='current_price',
            field=models.FloatField(null=True),
        ),
    ]
