# Generated by Django 3.1.3 on 2021-07-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auction_listing_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
    ]
